First commit, did some fixes
feedme-swent-epfl/feedme-android pull request #111
Opened 2024-04-26 23:24 UTC by ohamz

First draft of small fixes needed to be done:

- [ ]  Modify BottomNavigationBar color to match color template.
- [ ]  Adapt the Rating Icon in Landing Page (Recipe card).
- [ ]  Adapt the Save Icon in Landing Page (Recipe card).
- [ ]  Adapt Icons in Camera Preview.

Related issue : https://github.com/feedme-swent-epfl/feedme-android/issues/99#issue-2264064902

2024-04-28 17:50 UTC, ohamz commented
More fixes:

- [ ] Change the BottomBar Icons and remove labels to match the figma
- [ ] Fix UI of SmallThumbnailsDisplay (Icons and layout)

2024-04-28 18:48 UTC, ohamz commented
Will check the changes made later to fix the tests, probably linked to the Text composables.

2024-04-29 23:38 UTC, ohamz commented
This PR is ready for review.

2024-04-30 09:44 UTC, FacerOfGod requested changes
The fixes appear to be well executed. They're certainly going to enhance the user experience. One minor aesthetic tweak I'd suggest is adding a bit more padding to the white box when a button is selected because it is currently touching the edge of the screen. If this requires a lot of effort, we can disregard it for now and do a fix later. Other than that great work! :D 

<img width="67" alt="image" src="https://github.com/feedme-swent-epfl/feedme-android/assets/93382197/bd312ec8-51ab-4bad-b0e5-818c5dbd83b7">

2024-04-30 09:53 UTC, mche3kek requested changes
Very nice improvements to the UI and the code, small comments and variables to check to be consistent across all files and I am unsure about the new name for the create screen.

Great job overall !

2024-04-30 09:53 UTC, mche3kek commented on app/src/main/java/com/android/feedme/ui/SavedScreen.kt
It is only the UI, the functionality is still not enabled right?

2024-04-30 11:32 UTC, ohamz commented
> I'd suggest is adding a bit more padding to the white box when a button is selected because it is currently touching the edge of the screen. If this requires a lot of effort, we can disregard it for now and do a fix later. Other than that great work! :D

I'll work on it.

2024-04-30 11:34 UTC, ohamz commented on app/src/main/java/com/android/feedme/ui/SavedScreen.kt
Yes

2024-04-30 11:38 UTC, ohamz commented on app/src/androidTest/java/com/android/feedme/screen/FindRecipeScreen.kt
We can decide in a few hours during the Standup meeting.

2024-04-30 14:43 UTC, mche3kek approved these changes

2024-04-30 14:44 UTC, mche3kek commented
Good job with correcting the errors, we will discuss the terminology of find_recipe with the team and fix it if needed in another PR

2024-04-30 14:49 UTC, FacerOfGod approved these changes

2024-04-30 14:49 UTC, merged