Python script to upload recipes to database
feedme-swent-epfl/feedme-android pull request #189
Opened 2024-05-17 08:23 UTC by 0marwa

This python script was ran on my laptop and allowed us to upload the recipes to the FireStore Database (: 
Small fixes following the script : changing the `recipe` path to allow us to fetch from the right `collection` in the Database

2024-05-17 18:02 UTC, mche3kek requested changes

2024-05-17 18:02 UTC, mche3kek commented on scraping/updated_recipes.json
Is this the updated file with the description filled by ChatGPT or not ? If not could we add that instead ?

2024-05-17 18:02 UTC, mche3kek commented on scraping/fill_db_recipes.ipynb
The script looks good to me, only thing I want to point out is that the paths are customized to your laptop, wouldn't it be better to have a relative path relevant to our project structure instead so that anyone can run the script ?

2024-05-17 20:49 UTC, xrsula commented
The script needs some updating because of the new way we want to store the recipes in the database. Since I was the one that dealt with the creation of the recipe.json and the upload of the ingredients in the database, I will commit a small fix that will deal with that

2024-05-17 21:17 UTC, xrsula requested changes
This script looks great ! Apart from Mamoun's remark, I would say that you will now need to upload to the database the new recipe list that contains the curated ingredients. This thus requires a small change to the script :)

2024-05-18 17:41 UTC, 0marwa commented on scraping/updated_recipes.json
It's been added below!

2024-05-19 07:55 UTC, mche3kek approved these changes
Everything looks good to me !

2024-05-19 16:30 UTC, xrsula approved these changes
Looks good :) Thanks for the changes !

2024-05-19 16:31 UTC, merged