Implementing the Database and Data Model
feedme-swent-epfl/feedme-android pull request #23
Opened 2024-04-01 17:21 UTC by fdejean

The goal is to get usable Recipe and Ingredients objects for the UI that are synced with the database.
More detail about the data model can be found on the wiki / Notion

2024-04-01 17:22 UTC, fdejean commented
The test fail since the Authentication is not currently done, hence it cannot access the database.

2024-04-08 10:43 UTC, fdejean commented
I will only implement the UI such that the object are already define for the UI implementation

2024-04-08 12:22 UTC, mche3kek requested changes
I think that the model should be improved upon to avoid having inexact or unusable values for certain fields, I stay at your disposal to discuss the model implementation if need be

2024-04-08 12:22 UTC, mche3kek commented on app/build.gradle.kts
Instead of having id for the plugins, adding them to the libs file would be more suitable (especially for version management)

2024-04-08 12:22 UTC, mche3kek commented on build.gradle.kts
Same as for the other build.gradle.kts file, btw I can do it if you prefer

2024-04-08 12:22 UTC, mche3kek commented on app/src/main/java/com/android/feedme/model/data/Ingredient.kt
Maybe add a comment to explain what each field means, also might be interesting to use an enum for the ingredients type as they should be well-defined

2024-04-08 12:22 UTC, mche3kek commented on app/src/main/java/com/android/feedme/model/data/Ingredient.kt
Also for the id, is it only an internal component hidden from the user? If that's the case, wouldn't it be easier to have it as an integer for ease of comparison and such?

2024-04-08 12:22 UTC, mche3kek commented on app/src/main/java/com/android/feedme/model/data/Recipe.kt
Same remark for the recipeId regarding the ease of comparison

2024-04-08 12:22 UTC, mche3kek commented on app/src/main/java/com/android/feedme/model/data/Recipe.kt
I think that the detailedDescription component is not that meaningful (or could be replaced with a Step object).

It could be interesting to have a numberOfSteps / numberOfIngredients component for easier retrieval of these values for the short description of each recipe (e.h : This recipe contains x steps) or for the recipe suggestions module (e.g : you have x ingredients and you still need y)

Maybe change the val shortDescription to title in step ?

For the metadata, I think that measure should be in an enum as it can only be one of few select values, and quantity should be expressed as a number. Also, we can have the measure enum be specific to the type of the ingredient (e.g: if spice --> pinch, tbsp, etc)

2024-04-08 12:35 UTC, mche3kek requested changes

2024-04-08 12:35 UTC, mche3kek commented on app/src/main/java/com/android/feedme/model/data/Recipe.kt
Typo in difficulty

Time in a string will be tricky to parse, maybe a numeric value in minutes

Same remark for userid as the other ids

2024-04-08 12:36 UTC, fdejean commented on app/src/main/java/com/android/feedme/model/data/Ingredient.kt
Ingredient will not be well defined, as it will be hard to get a total list of them. I will add more comment too!

2024-04-08 12:37 UTC, fdejean commented on app/src/main/java/com/android/feedme/model/data/Ingredient.kt
Yes, it is internal, but it is best practice to use a String for Firebase

2024-04-08 12:46 UTC, fdejean commented on app/src/main/java/com/android/feedme/model/data/Recipe.kt
> I think that the detailedDescription component is not that meaningful (or could be replaced with a Step object).
The short description is for the thumbnail, but I agree that detailedDescription is not used in the Figma. Hence I will remove then
> It could be interesting to have a numberOfSteps / numberOfIngredients component for easier retrieval of these values for the short description of each recipe
I agree for numberOfSteps, but for the numberOfIngredients, this can simply be get by counting the element in the list. 
> For the metadata, I think that measure should be in an enum as it can only be one of few select values, and quantity should be expressed as a number.
Yes, good idea

2024-04-08 12:54 UTC, fdejean commented on build.gradle.kts
Yes, I will prefer that you do it @mche3kek. As I do not why some are specified and other not

2024-04-08 14:26 UTC, mche3kek commented
Everything looks fine to me, model might need tweaking after we begin scrapping recipes

2024-04-08 14:28 UTC, merged