Fridge Button
feedme-swent-epfl/feedme-android pull request #264
Opened 2024-05-31 18:29 UTC by FacerOfGod

**Goal :** Create a button were the user can save a list of Ingredients then modify it, generate recipes and then close the app and be able to reload the list that was saved.

- [ ] Create the UI 3 buttons
- [ ] Save the data in Cache
- [ ] Create test

Additional Feature : 
- [ ] The list of ingredients that is currently present when you close the app, will automatically appear with no effort needed by the user

PS: There are three buttons a save button that will save the list of ingredients. Then the load button that should allow you to reset the list of Ingredients that you saved. After that there is a delete button that deletes item in the list.

2024-05-31 19:25 UTC, FacerOfGod commented
The code has a security problem that is why SonarCloud failed :

> Security Issue : Encryption of Sensitive Data

It is linked with SharedPreferences.

2024-05-31 21:09 UTC, FacerOfGod commented
**Little bug discovered:** If you donwload the app for the first time no input box appear.

2024-06-01 13:55 UTC, 0marwa requested changes
Good job for the new feature ;) 
Not much to say on the code itself as it's clean, but a bit more documentation to help understand quickly what each function's aim would be very helpful! 
And a screenshot of the UI for Figma reference also if possible

Thank you in advance ((:

2024-06-01 13:55 UTC, 0marwa commented on app/src/main/java/com/android/feedme/model/data/Recipe.kt
Maybe document the newly-added functions to explain briefly their goal and functioning ?

2024-06-01 13:55 UTC, 0marwa commented on app/src/main/java/com/android/feedme/model/viewmodel/InputViewModel.kt
Same comment here ! The two main functions need some documenting in my opinion, other than that, the code looks clean

2024-06-01 14:10 UTC, FacerOfGod commented on app/src/main/java/com/android/feedme/model/data/Recipe.kt
I am going to delete these functions cause there were for testing purposes. Thanks for the heads up :)

2024-06-01 14:13 UTC, FacerOfGod commented on app/src/main/java/com/android/feedme/model/viewmodel/InputViewModel.kt
Yup, you are completely right. I will add documentation for retrieveSavedList() and saveList(). 👍

2024-06-01 14:41 UTC, FacerOfGod commented
Documentation has been added and a photo of the UI has been added to the description.

2024-06-01 16:44 UTC, 0marwa approved these changes
Thank you for changing the necessary details! I added a quick comment but I will approve the PR nonetheless as it's a very small remark. 

The new features implemented add a nice touch to the ingredient input process and enhance the user-expereience of the app, well done for thinking of it!

2024-06-01 16:44 UTC, 0marwa commented on app/src/main/java/com/android/feedme/model/data/Recipe.kt
okay, perfect then!

2024-06-01 16:44 UTC, 0marwa commented on app/src/main/java/com/android/feedme/model/viewmodel/InputViewModel.kt
just a quick question, in the line 61, instead of initialising the list with `null`, isn't it better to use an empty list directly ? just seems cleaner (:

2024-06-01 16:52 UTC, FacerOfGod commented on app/src/main/java/com/android/feedme/model/viewmodel/InputViewModel.kt
Nice question. `null` here represents an future-to-be IngredientMetadata which state life hasn't began yet. If there wasn't `null`. There will be no input boxes for the user to start with.

2024-06-01 16:53 UTC, merged

2024-06-01 20:13 UTC, 0marwa commented on app/src/main/java/com/android/feedme/model/viewmodel/InputViewModel.kt
noted, all good then!